# Generated by Django 4.1.1 on 2022-09-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentMethod',
            field=models.CharField(blank=True, choices=[('CASH', 'CASH'), ('TRANSFER', 'TRANSFER'), ('CARD', 'CARD')], max_length=27, null=True),
        ),
    ]
